// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi4WE93PZp0e8eqsSfF6RBE2iVOdzCQiY',
    appId: '1:809310900919:web:10a70e5529e2d570757332',
    messagingSenderId: '809310900919',
    projectId: 'book-ba8f9',
    authDomain: 'book-ba8f9.firebaseapp.com',
    storageBucket: 'book-ba8f9.appspot.com',
    measurementId: 'G-PQE0J9LSK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyePGRidO0207h7wOAe4D7fELw361lm1w',
    appId: '1:809310900919:android:6e2cd874d7a80e88757332',
    messagingSenderId: '809310900919',
    projectId: 'book-ba8f9',
    storageBucket: 'book-ba8f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvobTolrirotNwbtdhDthV2pmd9bVBkmc',
    appId: '1:809310900919:ios:570fd4a5c99bc9e1757332',
    messagingSenderId: '809310900919',
    projectId: 'book-ba8f9',
    storageBucket: 'book-ba8f9.appspot.com',
    iosClientId: '809310900919-70it1d0c6ls0q7r96vpaq0u6llhaflqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.book',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvobTolrirotNwbtdhDthV2pmd9bVBkmc',
    appId: '1:809310900919:ios:570fd4a5c99bc9e1757332',
    messagingSenderId: '809310900919',
    projectId: 'book-ba8f9',
    storageBucket: 'book-ba8f9.appspot.com',
    iosClientId: '809310900919-70it1d0c6ls0q7r96vpaq0u6llhaflqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.book',
  );
}
